### ISSUE TITLE
Integrate AliaksandrSiarohin's First Order Motion Model for Image Animation

### ISSUE THREAD

**Issue by ta-nelson** [deepfakes/faceswap#1001]
I am wondering if it would be possible to integrate this model into this project : https://github.com/AliaksandrSiarohin/first-order-model . The model does not seem to require as complex a data set to produce a quality deepfake (it seems to only require a video to train on and function with any face from there?), but it is designed targeting a very specific environment.  It is licensed under Attribution NC 4.0 International

**Comment by bryanlyon** [comment]
The first order model does not fit in the scope of Faceswap, which focuses on replacing one face with another.  First Order, on the other hand, re-animates or "puppeteers" a face.  This is unlikely to ever come to Faceswap, though we do accept PRs.

Further, a simple copy of the First Order Model into Faceswap is impossible, since the license that code was released under is incompatible with the GPL license we use.  Someone would have to reimplement it in a clean way for us to be able to accept it.

If that really interests you and you do it, we would be happy to review your Pull Request.
