### ISSUE TITLE
ImportError: cannot import name 'nullcontext'

### ISSUE THREAD

**Issue by pluzmedia** [deepfakes/faceswap#1049]
When it train I am having the following error
`File "/faceswap/faceswap/plugins/train/model/_base.py", line 14, in <module>
    from contextlib import nullcontext`
`ImportError: cannot import name 'nullcontext'`
I am using `python 3.6.8`

**Comment by torzdf** [comment]
Use python >=3.7

I will update our requirements to reflect this.

**Comment by ezavesky** [comment]
hi @torzdf, this causes some issues because there is no handy gpu tensorflow image with py3.7, can you maybe utilize the fix that is shown in [this SO post](https://stackoverflow.com/a/45187287)?

I ask *maybe* because I haven't fully confirmed the minor change for testing.  With an update of the `Dockerfile.gpu` to ``tensorflow/tensorflow:2.2.0rc2-gpu-py3`` the handy usage guide is working at least to the extract stage...

```
class NullContextManager(object):
    def __init__(self, dummy_resource=None):
        self.dummy_resource = dummy_resource
    def __enter__(self):
        return self.dummy_resource
    def __exit__(self, *args):
        pass
```
