### ISSUE TITLE
Have you tried using Keras Data Generator?

### ISSUE THREAD

**Issue by fcakyon** [deepfakes/faceswap#106]
Hello, i see this script uses extreme amount of gpu vram, this problem can be overcomed using Keras DataGenerator, this way script only uses 65 image at a time. Here is the link explaining it:
https://stanford.edu/~shervine/blog/keras-how-to-generate-data-on-the-fly.html

**Comment by facepainter** [comment]
@fcakyon ... the code is already using the Keras functional API to create a dense connected network rather than just using the standard Sequential model...also it already supports configurable batch processing.

**Comment by fcakyon** [comment]
No I dont mean that. Bu using Keras Data Generator, you can make model read images in batches instead of allocating vram for all of the training images at the same time. This way it always uses batch size of vram which would be sms'ler than 1gb.

**Comment by fcakyon** [comment]
If you train a model without a Data Generator implementation, script puts the whole data in vram/ram, then updates the weights in batches. However, with DataGenerator, it only puts the batch to vram/ram, and only after finishing current batch, it puts new input data to vram/ram, resulting in a significantly reduced vram usage.
After implementing a custom generator function, you perform the training with fit_generator function.
I can help on this topic if needed.
Keep the good work up! :)

**Comment by Clorr** [comment]
@fcakyon I find your link very interesting, and if you can provide a working version, feel free ;-)

The only thing I'm wondering here is that, as of now, we don't use `.fit(...)`, but `.train_on_batch(...)` which, AFAIK, loads only one batch at a time. Also it is done like this because the model is composed of one encoder and 2 decoders trained with separate data. I don't know if it is possible to use `.fit(...)` with such a configuration. But, again, feel free to propose. If it works, it will be accepted.

Note that the training data preparation is done in `lib/training_data.py` which I intend to heavily rework (after reading your link ;-) ), so please warn me if you intend to work on that soon.

**Comment by Clorr** [comment]
@fcakyon If you look at [this commit](https://github.com/Clorr/faceswap/commit/ae671067cae835cf71a928043dc19a891f0515c3) , you will find a new class named `TrainingDataGenerator` which could be a base for your modifications if you want

**Comment by facepainter** [comment]
@fcakyon @Clorr  ah - my bad, misunderstood - that is actually *super* useful!

**Comment by fcakyon** [comment]
@Clorr @facepainter Thanks for your interest and the new class :) I will try to understand your functions and classes better and then work on adapting a data generator class for our usage in my free times.
