### ISSUE TITLE
Ubuntu 16.04 fail install

### ISSUE THREAD

**Issue by shadowfolder** [deepfakes/faceswap#113]
I''m trying to build and run faceswap on fresh ubuntu install, (16.04.3 LTS), but im getting various errors.
Can somebody please tell me what's packets i need to install?
I've tried to installed cuda and nvidia driver(installed ok), but with python 3 and his dev and pip packages... Something is not enough.
docker build -t deepfakes . is not enough to run faceswap. Any tips?

**Comment by fat-tire** [comment]
**A NOTE ON USING THIS W/LINUX--**

I built tensorflow myself in Ubuntu 17.10 (x86_64), so I'm not going to get into the details of building from source, but a few things that the README doesn't note:

0.  If you are building from source, make sure you use `/usr/bin/python3` not `/usr/bin/python` when running `./configure`.  I won't go into how to do the rest as the [official instructions](https://www.tensorflow.org/install/install_sources) are pretty good. (If you're not building from source you won't get all the benefits of an optimized build for your specific machine.)

1.  You'll also need to `apt-install cmake` before installing the python modules.

2.  You need to use `pip3` and not `pip`, since deepfakes uses python3 not python 2.7

```
sudo apt-install cmake
pip3 install scandir
pip3 install pathlib
pip3 install h5py
pip3 install Keras
pip3 install opencv-python
pip3 install tqdm
pip3 install face_recognition
```
3.  If you are going to use the gpu and you have an nvidia driver (and are installing the cuda 9.1 and cudann packages from nvidia) you probably want to use the latest 387 version driver.  For me that was 387.34.   I got a black screen on boot using the standard 387 -- the fix was to `sudo add-apt-repository ppa:graphics-drivers` first and then I got the driver that worked.

4.  So if you're NOT building you'd do `pip3 install tensorflow` and maybe `pip3 install tensorflow-tensorboard` if you want the nifty web visualizer thing.  I had thought there was a tensorflow-gpu too but what do I know..

5.  There seems to be a bug with `faceswap.py` and python3 in 17.10 that required a small change.  There's actually a better way to fix this, but this works if you run into a crash on the last line about missing 'func'  (yes, I am bringing you the 'func').  Just add:

    parser.set_defaults(func=exit(0))

above the 2nd-to-last line in the file:

    arguments= parser.parse_args()

Basically this is what the program does if you don't give it any arguments.  So you're just saying to exit.  You can also make a function like:

def need_more_args(args):
    print('Use an argument:  [ extract | train | convert ]')
    exit(0)

Then you could change that 3rd-to-last-line to:

    parser.set_defaults(func=need_more_args)

6.  There are minor other issues, such as the input file containing the raw images should be called `/input` not `/src` and the faces are placed in `/output` not `/extract`.  But whatever.  You can override that with `-i` and `-o` for the input and output directories.  (or -A and -B for the two faces directories when training.  Both `-A` and `-B` default to `/input` I think, so be careful)

All that said, I'm still playing with this myself, but I hope this helps.

**Comment by Clorr** [comment]
@shadowfolder the docker file helps for the general setup, but the most important thing is to install the requirements located in `./requirements.txt`

If you want to use the GPU, install ./requirements-gpu.txt as well as CUDA and CuDNN (see https://yangcha.github.io/Install-CUDA8/)

Note that GPU is not supported in Docker unless you adventure yourself with nvidia-docker.

If you have errors, report them explicitly or we won't be able to help you

**Comment by Clorr** [comment]
@fat-tire thanks for all these info, feel free to add them in the INSTALL.md, or even create a new file like INSTALL-UBUNTU.md

**Comment by shadowfolder** [comment]
@fat-tire HUGE thanks mate! Now i finally installed it and run it without any errors. Damnit, this takes me over 40 hours to figure it out and with your help i did it. Now i know where was error. Also thanks @Clorr

**Comment by Clorr** [comment]
Please report how you fixed this in this thread, if you think it may help other users
