### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by cdalexndr** [deepfakes/faceswap#1138]
Installer doesn't add entry to windows apps to uninstall.
Installer should also have uninstaller.

**Comment by bryanlyon** [comment]
From the FAQ.  https://forum.faceswap.dev/app.php/faqpage#f1r2

How do I uninstall Faceswap?
Faceswap is deliberately installed "standalone" so that it doesn't interfere with the rest of your computer. To uninstall, simply delete the folder that you installed Faceswap into.

Then if you want to you can also uninstall MiniConda (the only 3rd party app that we install) the usual way.

**Comment by cdalexndr** [comment]
An uninstaller would be more user friendly.

**Comment by torzdf** [comment]
It would.

Until it destroys someone's carefully curated Conda environment for an entirely separate project because it was flagged for uninstall.

Faceswap is not a compiled Windows application. It does not appear in Windows programs. It does not touch the registry. It exists *purely* to make the installation process easier.

I could always remove it. That would solve the uninstall problem.

Decisions, decisions.

**Comment by cdalexndr** [comment]
I see... but...
If installer is for non-expert end user, shouldn't the expert ones that already have conda env setup, install using some scripts instead of trusting an installer to do some magic conda env setup?

I would expect installer to install all non-windows dependencies inside the `faceswap` folder to not conflict with other conda environments. This way, a safe uninstaller could be made.
For expert users, they will install using some scripts that use the shared pre-install conda environment.

This way, the setup is encapsulated, install and uninstall.

Having said that, the current uninstall is easy enough, but instructions are hidden inside FAQ. 
A link should be added to [install instructions](https://forum.faceswap.dev/viewtopic.php?t=20).
