### ISSUE TITLE
Adjusting Nodes and Layers?

### ISSUE THREAD

**Issue by yoolandes** [deepfakes/faceswap#117]
Is there a way to adjust nodes and layers before starting the training?

**Comment by Clorr** [comment]
There is no parameter to modify the model, because the model files can only be reloaded if the parameters stay constant. If you want to do so, you have to modify directly the `Model` file in the `plugins` folder.

**Comment by Clorr** [comment]
The question is: what is your global understanding of the code, and what is your intention here?

If your problem is that you have not enough memory to run the model, you should use the LowMem plugin instead of modifying things.

If you want to play with the model and adjust yourself the params, I would assume you have enough background to do so...

**Comment by yoolandes** [comment]
My intention is to use this code here instead of the FakeApp GUI. And now I want to figure out where I can find the parameters "Layers" and "Nodes" in the faceswap code.

**Comment by Clorr** [comment]
FakeApp has it's own codebase, so I'm not sure of what it did behind those parameters

**Comment by yoolandes** [comment]
Hmm okay. Anyway thank you for your help.
