### ISSUE TITLE
alert opening faceswap gui on linux ubuntu

### ISSUE THREAD

**Issue by gravitydeep** [deepfakes/faceswap#1228]
Hello

Failed to extract font properties from /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: In FT2Font: Could not set the fontsize (error code 0x17)

but the interface works

**Comment by torzdf** [comment]
1) When filling out bug reports please use the template provided (shown below). Single line extracts tell us nothing.
2) This is not a bug. It is a warning message generated by matplotlib when it scans your font directory, Please feel free raising to raise an with their project: https://github.com/matplotlib/matplotlib


## Bug report template:

*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Python Version [e.g. 3.5, 3.6]
 - Conda Version [e.g. 4.5.12]
 - Commit ID [e.g. e83819f]
 - 
**Additional context**
Add any other context about the problem here.

**Crash Report**
The crash report generated in the root of your Faceswap folder
