### ISSUE TITLE
Which is the ground truth of generation image？

### ISSUE THREAD

**Issue by tjusxh** [deepfakes/faceswap#126]
In my understanding, the project achieved that change A's expression by B's expression. In the project,the train command is python faceswap.py train -A ~/faceswap/data/trump -B ~/faceswap/data/cage -m ~/faceswap/models/. I can't find the ground truth when training. What's the target of the generation image? Thanks

**Comment by dfaker** [comment]
Both autoencoders are being trained to transform a warped and distorted version of an individual's face into an undistorted version, the ground truth is the undistorted face.

Being able to convert from one face to another is a side effect of the network interpreting A's face as a distorted image of B and "correcting" it.

**Comment by tjusxh** [comment]
Thanks your answer. If we input A and B. Did the project want to get the combination of A's identity and B's expression and the combination of B's identity and A's expression? If yes, the undistorted  face may be not A.

**Comment by dfaker** [comment]
No, the project just wants to get an restored version of A and an restored version of B.

I does the restoration of the input by using all the hints it can including looking for warped expressions and warped lighting cues, the face swapping is a transfer task that happens by "accident" when rather than feeding a distorted version of A into A's autoencoder we feed in a B, the network interprets the image of B as a distorted A and attempts to "fix" it to look like A again.
