### ISSUE TITLE
Faceswap doesn't use RX 7900 XT

### ISSUE THREAD

**Issue by RPochyly** [deepfakes/faceswap#1348]
**Describe the bug**
When trying to extract faces, Faceswap falls back to CPU with this message: 
2023-08-31 15:12:03.523307: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1990] Ignoring visible gpu device (device: 0, name: AMD Radeon RX 7900 XT, pci bus id: 0000:03:00.0) with AMDGPU version : gfx1100. The supported AMDGPU versions are gfx1030, gfx900, gfx906, gfx908, gfx90a.

**To Reproduce**
Start face extraction with any settings (in my case it were s3fd, fan and vgg-obstructed)

**Expected behavior**
The extraction should use the RX 7900 XT

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Python Version 3.10.12
 - Conda Version 23.5.2
 - Commit ID 5d00025

**Comment by torzdf** [comment]
You do not give enough information here about the version of Faceswap you are using. I have to take a guess an assume ROCm.

Either way (and assuming that you are using ROCm) then the issue is clearly stated in your error report:
The supported AMDGPU versions are gfx1030, gfx900, gfx906, gfx908, gfx90a

You would need to take this up with the ROCm developers.
