### ISSUE TITLE
An update for current python versions [Linux]

### ISSUE THREAD

**Issue by XDM-Inc** [deepfakes/faceswap#1395]
because of the updating of python the linux version no longer works because it is asking for the older version of python.

**Comment by torzdf** [comment]
Don't use system Python. Use the Linux installer and/or Conda if you want to install manually and be able to run different versions of Python

**Comment by XDM-Inc** [comment]
> Don't use system Python. Use the Linux installer and/or Conda if you want to install manually and be able to run different versions of Python

i tried followed the instructions from the sh file. you cant get away from the python requirement. i also cant make it select different versions of python that i have installed as it only wants to use the system one. and i cant downgrade the python on my system as its a system app that other system apps depend on.

**Comment by torzdf** [comment]
>  you cant get away from the python requirement.

This is just plain incorrect. You can and we do. We use Conda *specifically* because it allows you to use different versions of Python, and manage different local Cuda installs.

If you want to run a newer version of Python, then you are going to need to take it up with Tensorflow, as the last version that supports Windows, natively, is 2.10. The highest version of Python that this supports is 3.10. 

Ultimately, I am a Linux user myself. My system Python is version `3.12`. I also run (and develop) faceswap. This runs, in Conda, on version `3.10`.

We will **only** provide support for people who follow the standard install procedure and manage their faceswap install through Conda.

That is not to say that you can't run it with system Python, just that we will not support it.

**Comment by torzdf** [comment]
If you want to discuss this further, you are welcome to engage with me on Discord, where I replied to your message. Ultimately this issue is closed because it is not a bug.
