### ISSUE TITLE
Recent git pull includes Gan support but no relevant documentation.

### ISSUE THREAD

**Issue by fetchlister** [deepfakes/faceswap#169]
I am trying to use GAN support in my faceswaps as my previous attempt of 3 days of training yeilded terrible results with 3k pictures (a good blend) for each target. I see that the python scripts are there but running them produces no output and USAGE.md has not been updated to reflect the extracting, training, and converting process for use with the GAN plugin.

Using a GPU on linux with python version 3.6.4
Latest available Faceswap.

**Comment by LordVulkan** [comment]
For the training process just add:
`-t GAN`

For converting add:
`-t GAN -c GAN`

**Comment by fetchlister** [comment]
@LordVulkan does GAN require any new dependencies?

**Comment by LordVulkan** [comment]
No new dependencies and the preview works for me.

What output log are you getting?

**Comment by fetchlister** [comment]
Neverming. I had to add bs=32. Din't hit me that the loss of preview was related to the out of memory error.

so just to clarify, add -t GAN when training and then -t GAN -c GAN when applying trained model to a directory of frames of say, a video to replayes the faces?

**Comment by LordVulkan** [comment]
Yes.

-t is from trainer and -c is from converter.

**Comment by fetchlister** [comment]
Is there an established threshold for loss numbers with the GAN plugin yet? I'm getting two sets of numbers now instead of just one. usually people say stop around 0.09, should  I ignore the Loss_GB value or what?

**Comment by LordVulkan** [comment]
I don't know much about GAN, but if I'm not wrong it uses two models, a generator and a discriminator.

Loss_GX should be the value for the generator and Loss_DX for the discriminator.

I don't know what values should be considered acceptable as the discriminator values are constantly jumping, and during my tests the generator values are stuck at around 0.17 after ~15 hours.

**Comment by shadowfolder** [comment]
What GAN really does? Improving quality?

**Comment by LordVulkan** [comment]
It's a different algorithm, I'm not sure it produces better results by default, it needs more resources.

More info: https://github.com/shaoanlu/faceswap-GAN

**Comment by subzerofun** [comment]
I've let the training run with the standard autoencoder model until a loss value of 0.02, which produced pretty good output samples – a bit blurry, but this is probably due to some bad/compressed input images from my source A folder. Then tried the same with the new GAN128 plugin, as well as the 64px GAN plugin and both output samples had some weird artifacts: mosaic-like patterns, looking like jpeg compression artifacts (applied filters/features?). Will try both plugins again with different input faces, but for this test the standard model produced better results. But i guess with the right input material the GAN plugins should produce sharper images with more details. Don't know how long you have to train the model to get rid of the articfacts though.

**Comment by Clorr** [comment]
Feel free to discuss about this in https://github.com/deepfakes/faceswap-playground and/or make a Pull Request to improve documentation
