### ISSUE TITLE
GAN mask oversharped with dots

### ISSUE THREAD

**Issue by iperov** [deepfakes/faceswap#180]
~20h
is this normal behaviour?
![python_2018-02-11_15-19-34](https://user-images.githubusercontent.com/8076202/36072789-8173ea42-0f3f-11e8-8bc2-b2b8d8e9803b.png)

**Comment by dfaker** [comment]
The "dots" look like classic deconvolution artifacts, we might consider nudging the final two sizes and strides or sticking a tf.images.resize_images and a conv2d layer just before the final output layer.

The mask layer generally looks a little like edge detection, given that these faces have a good deal more high frequency features than any other sample set I've seen the GAN used on, I'm not sure this isn't the expected behaviour.

**Comment by iperov** [comment]
looks like GAN v1 model used in faceswap.
Can you port GANv2 with perceptual loss?

**Comment by iperov** [comment]
@dfaker hmm but man from here https://github.com/shaoanlu/faceswap-GAN/issues/50 told that is awesome mask

**Comment by dfaker** [comment]
They're certainly pretty but I'm not sure they're fit for the purpose of masking the replacement face, particularly how the curve of the eyebrow exactly follows Downey's eyebrow causing the mask to cut arbitrarily through Shia's. 

How does that translate to a mask meaning "Take from the original where I'm white and take from the GAN where I'm black."?

Equally why should there be any GAN output in the edges outside the face surely with an ideal mask that should be all from the original image?

**Comment by Clorr** [comment]
Maybe @shaoanlu has an answer ?

**Comment by hank-arus** [comment]
I had the same problem after I trained 36h (Model A 2000 pics, Model B 400 pics), 12h ago I added more Pics to Model A.  Luckily I backup the model files often.

**Comment by dfaker** [comment]
So the output seems not to be ideal for the purpose of masking the face regions, and more samples seem to reduce the issue.
