### ISSUE TITLE
MyFakeApp

### ISSUE THREAD

**Issue by p0sera** [deepfakes/faceswap#201]
Not an issue, but I am letting you know, that I created UI application for Windows x64. You can read about it here:
https://radek350.wordpress.com/2018/02/17/myfakeapp-fakeapp-alternative/
Let me know if it works or not. Thanks.

**Comment by iperov** [comment]
wow interesting... i will check

**Comment by flosth** [comment]
seems like a waste of time to create a significantly worse version of fakeapp for windows. fakeapp already runs on windows, why didn't you make one for mac?

**Comment by iperov** [comment]
@flosth this is faceswap build, not FakeApp.org.
I suggest app name MyFaceSwap :)

**Comment by p0sera** [comment]
I did this because the FakeApp didn't work for me @flosth. And I don't own a mac.

**Comment by Apollo122** [comment]
@flosth you are extremely rude.

**Comment by flosth** [comment]
@p0sera it worked for me, but either way the UI should be better and it should be crossplatform if you're trying to improve on fakeapp. 

@Apollo122 it's true though, for a second I was excited to see fakeapp going to more platforms but it's just a windows clone.

**Comment by gdunstone** [comment]
@flosth I see you have no contributions.
Contributions lend credibility to your criticism. 
If you want people to take you seriously, then I recommend you gain some credibility.

**Comment by p0sera** [comment]
I did this app for myself. If you want an app for a Mac then create it and share it @flosth.

**Comment by flosth** [comment]
@gdunstone i'm not a coder i just want to make deepfakes and i was hoping to see something new like fakeapp for mac. as it is this thing is just an uglier fakeapp. make one for mac and i will praise it.

**Comment by p0sera** [comment]
Yeah it is uglier, but you can set more thing on it.

**Comment by flosth** [comment]
@p0sera i can't create it because i don't know programming but if you do why don't you do it. we need a mac fakeapp, we don't need another windows fakeapp. this repo should be working on making new stuff not redoing stuff we already have.

**Comment by p0sera** [comment]
I can't do it because I don't own a mac dude :D

**Comment by flosth** [comment]
@p0sera seems like it has basically the same options just an extra "converter" option.

**Comment by flosth** [comment]
@p0sera well get a VM and get to work. i want to see smart people improve deepfakes but wasting time on what we already have is not the way man.

**Comment by p0sera** [comment]
Will you pay me @flosth ? I did this because the FakeApp v1 or v2 did not work on my PC. I have no motivation to create it for a Mac.

**Comment by p0sera** [comment]
Maybe next time I will not share this with other people...

**Comment by flosth** [comment]
@p0sera no i will not pay for a mac fakeapp because i didn't even pay for the windows fakeapp, that would be unfair. however i will say that it is good.

**Comment by flosth** [comment]
@p0sera nobody's talking about preventing you from sharing it man, look its fine but the people need a mac version right now not another windows version. i cant use it on my mac and i have to use it on my weak windows laptop, if you code that i wont have to.

**Comment by Alexander01998** [comment]
@flosth FakeApp doesn't run on Macs because they don't have Nvidia GPUs and don't support CUDA.
The only way to make this work would be to build some kind of Hackintosh machine with an Nvidia graphics card in it - and at that point you might as well build a Windows computer.

**Comment by flosth** [comment]
@Alexander01998 you guys are very smart im sure you could find a way. you and the fakeapp creator and people like @p0sera need to come together to build a mac version and you will make tons of money. i know you can do this.

**Comment by Alexander01998** [comment]
@p0sera Well, in theory one could re-write the entire thing to use OpenCL instead of CUDA, which could in theory run on a Mac. I have no idea how to do that though.

**Comment by flosth** [comment]
@Alexander01998 well lets get started.

**Comment by iperov** [comment]
@p0sera can you build same with face_alignment and pytorch ? from here https://github.com/deepfakes/faceswap/issues/187
bcuz default cnn sucks.

**Comment by p0sera** [comment]
I will not have time for this now @iperov. But if I will be bored some weekend I will have a look at it.

**Comment by p0sera** [comment]
But you can modify it yourself in Visual Studio solution and Advanced installer project if you want. The repo is here: 
https://bitbucket.org/radeksissues/myfakeapp

**Comment by flosth** [comment]
@p0sera no don't wait man, think of how much money you could make if you put it out for Mac. please start working on it, I will help

**Comment by subzerofun** [comment]
@flosth  **Why do you so desperately want a Mac version? And why exactly would it sell? Who would buy it? Even you've said yourself you wouldn't pay for it... Can you even discern between a macOS and iOS version?** After seeing the way you talk to people here i can't help but imagine a sixteen year old passive-aggressive teenager sitting in front of a greasy MacBook from 2012 with a CPU that takes 10 seconds to open an empty tab. No dedicated GPU of course. I guess if you could set up the repo yourself you wouldn't treat the people here like they are your _**potential tools**_.  And your idea to pitch them that they could be – ahem _business partners_ is really original.

You are rude because 1) you lack the tools and knowledge to realize even the smallest step of your plan _on your own_ and 2) people won't do what you say (probably because they are all stupid). Typical puberty mindset. Would be sad if you are older than 25.

But guess what, **i can write a faceswap-App in Swift, there are many ways to do this, maybe even with some kind of iGPU / dedicated GPU hardware acceleration** ([Apple's Metal](https://developer.apple.com/documentation/metalperformanceshader)):
* https://github.com/Octadero/TensorFlow
* https://github.com/PerfectlySoft/Perfect-TensorFlow
* Core ML: https://developer.apple.com/machine-learning/
* MPSCNN: https://developer.apple.com/documentation/metalperformanceshaders
* https://github.com/xmartlabs/Bender (iOS)
* etc.

Maybe i'll start it as a slow side project and post some screenshots of my progress here.

I've probably already tried to tell you this: Macs are not ideal for machine learning. And the most important part of the faceswap project is training the network with hundreds to thousands of high quality images until the model generates usable faces. Which takes aeons and runs the fastest on a GPU with a high clock rate, a lot of VRAM and a high shader count. Which most Macs don't have.

**You want to make money with this great App, don't you?** Who would buy it when their devices are too slow to generate finished face-swapped videos fast enough? The result would have to be instant that people pay for it.

**OK, so say you had your damn Mac App – finished, perfect and ready to sell.**
You won't make any money with it because Apple would not allow an App with such negative publicity in their App Store. Neither on mobile, nor desktop.

Didn't you witness the media hysteria after the Watson video? And no, negative PR is not good PR for your potential App. Not in this case. Because it affects Apple's most important value: **Their image**.

And regarding iOS: a smartphone does not have the processing power **to train** a neural net like this, not without draining the battery and overheating the CPU. Inference is possible, but you'd still need the trained models. How to create the models / where would you get them? And where to put all the data when your device can't handle it?

- **Input A**: You need probably multiple videos of person A (at least one with a lot of angles), upload them to external servers for further processing. Big Problem: Does the App's user have consent of person A to upload the data? What if not? Data still gets processed.

- **Best case scenario: Use for celebrity-faceswap:**
 Happens server-side: you need to build a model with hundreds of photos of say, Nicolas Cage. Nearly every photo or movie still of him is in some way rights managed. So you, as the App selling company, are not allowed to use these photos for commercial purposes **unless you buy the rights**. Good luck negotiating with Hollywood. 

- **Worst case scenario: Use for _celebrity_ faceswap**:
 Serverside: a nudity checking algorithm blocks the user from editing person A's face on some p*rn clip. Problem: What happens if the nudity filter can get bypassed? What if it is too restricting? What if this would be the only feature people would pay for?


Do you maybe remember the shitstorm Apple got into due to leaked "The Fappening" photos/videos? People then started realizing that uploading naked photos of yourself ~maybe~ is not best way to use your iCloud space.

> [Vulnerability in Find My Phone service and weak passwords may explain alleged celebrity photo leaks](https://9to5mac.com/2014/09/01/vulnerability-in-find-my-phone-service-and-weak-passwords-may-explain-alleged-celebrity-photo-leaks/)

- https://news.ycombinator.com/item?id=8251945
"September 2, 2014 – Kirsten Dunst blames Apple for nude hacking"

---

Uhm and Apple has Guidelines too:
https://developer.apple.com/app-store/review/guidelines/


> 1. Safety
> 
> When people install an app from the App Store, they want to feel confident that it’s safe to do so—that the app doesn’t contain upsetting or offensive content, won’t damage their device, and isn’t likely to cause physical harm from its use. We’ve outlined the major pitfalls below, **but if you’re looking to shock and offend people**, the App Store isn’t the right place for your app.

> 1.1 Objectionable Content

> Apps should not include content that is offensive, insensitive, upsetting, intended to disgust, or in exceptionally poor taste. Examples of such content include:

> 1.1.1 Defamatory, discriminatory, or mean-spirited content, including references or commentary about religion, race, sexual orientation, gender, national/ethnic origin, or other targeted groups, **particularly if the app is likely to humiliate, intimidate, or place a targeted individual or group in harm’s way**. Professional political satirists and humorists are generally exempt from this requirement.

**Comment by p0sera** [comment]
Guys can you help me, is it possible to use CNN on GPU? Is it possible with this repository? Will it be faster? What I know is that it is possible to use GPU for tensorflow package, but this package is not used for finding faces in an image.

**Comment by gdunstone** [comment]
@p0sera You need to build dlib with Cuda support and use the cli option to use cnn.

**Comment by p0sera** [comment]
@gdunstone thanks

**Comment by deepfakesclub** [comment]
Thank you @p0sera, this looks fantastic.
Open source, updated algorithms and functionality, lightweight, putting your name behind it. Much respect.
I'll start testing this out and try to support you with publicity and documentation.

To the other users: Yes, the face alignment is still a bit of an ongoing issues, but it shouldn't be too hard to port over once the repo here resolves the issue. I, too, find that the CNN extractor from face-alignment is the current best version (with GPU support, of course). 

If you have issues building dlib under Windows, use the most recent github from davisking. You need to install boost (this is the non-obvious part) and cmake beforehand. Then, I believe you can just use setup.py and include the switches to build with CUDA (and AVX if desired).

Ignore the trolls. Is there a moderation tool...

**Comment by LexCybermac** [comment]
@p0sera Perhaps not the best place to ask but is there a reason as to why my previews when training with the GAN model will fail to show up half the time?

https://i.imgur.com/51HcVZd.png

**Comment by Ianmcmill** [comment]
@p0sera from which state of faceswap did you create this?

**Comment by potholiday** [comment]
@p0sera  Can I ask why bitbucket and not github? github has more users than bitbucke

**Comment by kellurian** [comment]
@p0sera I tested your app with the addition of the multiGPU addition code I added to the Model_Original.Py file and it works great. You could add a plugin option for multi-GPU on your next version if you like. I think your app works great and is far less buggy than fakeapp.

**Comment by Kirin-kun** [comment]
FakeApp is better at detecting faces than faceswap is. It detects more faces than the HOG here. Cnn is almost as good, but is plagued by zoomed faces and wrong landmarks.

Unfortunately, the alignment files are not compatible, so one can't use both applications.

**Comment by iperov** [comment]
`Cnn is almost as good, but is plagued by zoomed faces and wrong landmarks.`
your information is outdated.
Check last commits.

**Comment by Kirin-kun** [comment]
I think this issue can be closed. Looks like the author got overwhelmed and doesn't plan to update it.
