### ISSUE TITLE
Rewritten in OpenCL

### ISSUE THREAD

**Issue by flosth** [deepfakes/faceswap#202]
i am starting a project to make deepfakes available to mac users. we will need to rewrite in OpenCL. who is ready to get started and get this thing on mac!

**Comment by flosth** [comment]
@Alexander01198 what do we do first?

**Comment by Alexander01998** [comment]
@flosth Like I said, I have absolutely no idea how to do that.

**Comment by Tyrannosaurus1234** [comment]
Nothing needs to be rewritten to use OpenCL, the deepfake scripts are platform-agnostic, you just need to use an OpenCL-capable build of Tensorflow. The dev/amd_gpu branch of Luke Iwanski's Tensorflow fork works.

**Comment by flosth** [comment]
then get a mac version going

**Comment by Tyrannosaurus1234** [comment]
Do it yourself. Oh wait, you can't - you don't know anything about programming. Open-source projects are a game of give and take, no one is going to do things for you unless you put in some work yourself, actual work, not "management".

Regardless, you're barking up the wrong tree, OpenCL support is not a Faceswap issue, it's a Tensorflow issue.

**Comment by flosth** [comment]
my work is coming up with the idea to post to mac, now it's time for others to help out

**Comment by GSonderling** [comment]
@flosth Try to be little considerate, we are doing it in our free time, for fun, you know.

Anyway I don't think this is a place to ask for it and I don't think it is necessary. I would propose closing this issue.

**Comment by subzerofun** [comment]
@flosth What are you waiting for? It already works on macOS. I'm training a model on 10.12 right now. 

![grafik](https://user-images.githubusercontent.com/17863119/36346824-2c111be4-1447-11e8-8a35-93aa3389aaae.png)


Python, Keras + Tensorflow are cross-platform. I could write an UI for it in Swift – but why 😇 ?

- Follow the install instructions of the faceswap repo
- Compile/install an OpenCL Tensorflow version:
https://github.com/hughperkins/tf-coriander
https://github.com/hughperkins/tf-coriander/blob/master/doc/installation.md
or one of those:
- https://github.com/lukeiwanski/tensorflow-opencl
- https://github.com/benoitsteiner/tensorflow-opencl

- read how to gather, extract and process training data
- 15min lookup on how to use the macOS Terminal 
- aaand 20 hours later you're ready to start training!
- start training on a macBook Air
- realize Tensorflow is just utilizing your CPU after all
- build zero-point energy nuclear research reactor for constant power
- plug in power adapter
- put yourself in cryostasis
- wake up in the year 2045, lose most of your limbs due to hypothermia
- look at training results
- Scarletts face still looks like a mole rat with 1000% jpeg compression
- look out the window
- realize the sun is now covered in a dyson sphere
- let the nanites absorb you into the singularity
- advice for the afterlife: be nice and reasonable when you ask questions and maybe people will help you (this is an "Issues" section and OpenSource generally doesn't follow the The Pyramid of Screaming)

Besides, most Mac hardware is not really made to train models like these for hours. Only Mac Pros fitted with newer GPUs, high-end iMacs with a new AMD GPU >2GB and the iMac Pro (which only a handful of people have considering its absurd price) would have enough processing power and VRAM to train a model in an **acceptable** timeframe. Even the newest $ 2,799 MacBook Pro only has a GPU with 4GB VRAM, which is not made to operate a few hours under 100% load. But if you want to melt a ~3000$ device just for swapping some faces – why not?

**Comment by gdunstone** [comment]
I am closing this because it's absurd.
