### ISSUE TITLE
Question about converting

### ISSUE THREAD

**Issue by isleon** [deepfakes/faceswap#244]
When I use the seamless mode the progress is getting very slow. 720 pics took about **1h30mins**.

**But** , if I first extracted the face of the photos to folder1, it takes about **5mins**. 
then convert the extracted faces with  seamless mode, it only takes **2 mins**.  ??? and the result is good.

To me this is pretty wired, put the converted face back on takes 1h20mins?? 

**Using GTX1080ti with 11GB ram**

thanks!

**Comment by Kirin-kun** [comment]
Well, in one case it ran the extractor inside the converter and in the other case it just read the alignments file? So, faster.

And the seamless mode takes notoriously a long time. It can multiply the time fourfold. 

Actually, I find that seamless rarely looks good on a video : it make the colors flicker a lot, since it calculates the colors for each image individually and not in context.

I think I read somewhere that it should be possible to take a predictive approach, by analyzing the images on a sliding window to calculate the color correction, but I don't know the specifics.

**Comment by iperov** [comment]
@Kirin-kun I see filcking with seamless mode only if celeb face noticeably narrow than porn face.

**Comment by oatssss** [comment]
@Kirin-kun what might work to get rid of the flickering is use seamless clone first, then on top of that histogram match using a filter based on the previous frame's histogram to try and smooth out the flickering.
