### ISSUE TITLE
Special request to make things easy.

### ISSUE THREAD

**Issue by nerdprogrammergm** [deepfakes/faceswap#26]
I request you to give steps by step instructions to work around with this project.
I am a JAVA and Nodejs guy but interested in AI/ML stuff and noob to python.
I am sure there are many people like me around the globe so I request you to give more details as for me env is perfectly setup but the project files when run are throwing errors.
Once I am handy with its working I will assist in this project with you all.
Thanks in advance.

**Comment by Ganonmaster** [comment]
This sounds like a cry for help, rather than a coherent question. Would you like to rephrase your question? Perphaps specify the steps you've taken, and where you're experiencing issues?

We're working to improve our documentation, but it's really too early to have this work out of the box for new users. Batteries are NOT included.

**Comment by nerdprogrammergm** [comment]
Well, you can say whateva you want to sounds like cry for help or blah blah blah, idc, what I care about is I am keen to lean this and I am trying my best to figure out the things.
If you can show me path to get it in working state, I will be glad and thankful else, still thanks for replying!
I just run the new files with the command mentioned in the readme.md. And it gave me th above mentioned error!

**Comment by deepfakes** [comment]
Hi @nerdprogrammergm ,

As @Ganonmaster stated, and as you know it as programmer, it is not always easy to do user friendly things. This project uses advanced libraries and those are not really easy to package for now.

So for now, all we can do is improving usage (and the project is already easier to use than before), but we can't promise about a "super easy" solution.

Also note that the project is collaborative and everyone coming here should consider that it is not done by super Python programmers who just don't care about end user. I'm also a Java programmer, and tackled C# or NodeJs from time to time, but never did Python. I spent hours to find out things and that's the way it is for now. Also @Ganonmaster  spent many hours to improve things so he deserves much gratitude for that.

Now if you are trying hard to get the project running, just come here, or on the 'faceswap-playground' repo and request for help in a detailed manner with a description of your error so that we can give you a constructive answer that will also help later newcomers.

Thanks for your understanding
