### ISSUE TITLE
During step of converting, it has error 'can't create frames'

### ISSUE THREAD

**Issue by ydeng11** [deepfakes/faceswap#295]
Does anybody has the same issue? I have finished training but cannot swap faces for video.

Thanks!

**Comment by bryanlyon** [comment]
During creation of your issue, the following messages were in the textbox by default.  We need the information to help.  Please read it and fill it out completely.

**Note: Please only report bugs in this repository. Just because you are getting an error message does not automatically mean you have discovered a bug. If you don't have a lot of experience with this type of project, or if you need for setup help and other issues in using the faceswap tool, please refer to the [faceswap-playground](https://github.com/deepfakes/faceswap-playground/issues) instead. The faceswap-playground is also an excellent place to ask questions and submit feedback.**

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 2.7, 3.5, 3.6.4, ...
- **Faceswap version:** commit hash or version number
- **Faceswap method:** CPU/GPU
- **Other related issues:** #123, #124...
- ... (for example, installed packages that you can see with `pip freeze`)

**Comment by Kirin-kun** [comment]
The "can't create frames" thing seems to be out of MyFakeApp when it's attempting to remake the original video.

I don't think you will get support on this side project here. Radek stopped developping it and the scripts it uses are outdated (cf https://radek350.wordpress.com/2018/02/17/myfakeapp-fakeapp-alternative/)

**Comment by Clorr** [comment]
Please reopen in playground if necessary
