### ISSUE TITLE
Reduce the model

### ISSUE THREAD

**Issue by Yuxishan2** [deepfakes/faceswap#297]
Does reconstruct the structure of auto_encoder by the concept of shufflenet a good idea?
With a smaller model, more people can use it to make remarkable 
videos.

**Comment by Clorr** [comment]
It is possible to add as many plugins as we want so if you can implement something it can be added to the repository

**Comment by bryanlyon** [comment]
ShuffleNet is an optimization for running Neural Networks on a phone or other portable low power device.  This is not going to help what we're attempting to do with faceswap since we are spending our time training a model, not just running one.  Due to the fact that almost all effort is spent on training, a shufflenet is not an appropriate solution.

**Comment by Yuxishan2** [comment]
@bryanlon  You have a very good point, the training process will take a lot of time, and no one will train the models on mobile phones.so the shuffle net may bring very little benefits. But for someone who don't have good gpus on their computers, if they have an option that using shuffle to train their models and do the inferences, it may save them a lot of time.

**Comment by bryanlyon** [comment]
Sadly, shufflenet is not faster to train than a "normal" model.  In fact, it takes additional work after the model is trained.

To do this on a phone is simply impossible.  To do this on a computer without GPUs is simply not feasible.  Unfortunately, CPUs just don't have the speed necessary to train models in reasonable time.  If you want to train a model without GPUs, you're welcome to use faceswap as it is, simply install the CPU requirements instead of the GPU, but note that it'll take upwards of months to train a single model using just the CPU.
