### ISSUE TITLE
Missing files on alignments.json

### ISSUE THREAD

**Issue by waltergammarota** [deepfakes/faceswap#302]
Hello,

I'm not sure if it is a problem, or just my lack of knowleadge, but when I use the alignments.json file to convert images, it skip some of the files from my batch, resulting in an incomplete set (with missing files in between).

Not sure how to interpret this behaivor, I know the aligment file is generated when I extract the faces from the frames, before starting the training process, but what it means the missing files? Is because the extract wasn't able to detect faces on some of the frames? Any idea how can I debug or fix?

Cheers.
Thanks.

**Comment by bryanlyon** [comment]
Look at the messages during the convert, it'll tell you any files it doesn't convert and why.  Usually, yes, it's because it doesn't find faces.  One thing you can do is run extract again with --skip-existing and different options selected to try to find more faces.  CNN works better than hog and finds more faces.  Rotation also night help.  Try different options to find more faces and figure out what works for you.

**Comment by ruah1984** [comment]
i think when extract, off the --skip existing, it may help.
