### ISSUE TITLE
histogram matching doesnt help

### ISSUE THREAD

**Issue by iperov** [deepfakes/faceswap#304]
model original

source:
![01484](https://user-images.githubusercontent.com/8076202/37646078-13b32200-2c42-11e8-9d3c-afd7e8873440.png)

dest:
![out00168 3](https://user-images.githubusercontent.com/8076202/37646091-17939cce-2c42-11e8-8091-64dd08c63dc7.png)

converted:
![out00168](https://user-images.githubusercontent.com/8076202/37646081-155ee2b0-2c42-11e8-809c-50ce93b0625b.png)

^ look at yellow-blue border, it same as source face

**Comment by iperov** [comment]
why we cant cut face from yellow background and overlay it with alpha ?

**Comment by iperov** [comment]
ow, problem it needs to keep source alignments :(

then suggest : extract cutted faces to RGBA png, because we need no background of source faces.

**Comment by Kirin-kun** [comment]
That's what we were talking about in #270 

Do you have the debug landmarks of source face?

I think dlib's cnn detected larger face than it is really.

**Comment by iperov** [comment]
faces were detected correctly

**Comment by Kirin-kun** [comment]
Landmarks are what is used at convert time. But the landmarks are not hard truth, they are often inferred by the face detector, like shown [here.](https://github.com/deepfakes/faceswap/issues/270#issuecomment-372133604)

And the destination face isn't cut before applying new face. That's why, when using really high blur value, the original face features shows through.

So, maybe there's some work to do to mask occlusions and background at convert time, to know what belongs to the face and what doesn't.

**Comment by iperov** [comment]
trained GAN (64)
and merged without mask

```
new_face = fake_output[:,:,:, 1:]
# new_face = mask * new_face + (1 - mask) * normalized_face
new_face = numpy.clip((new_face[0] + 1) * 255 / 2, 0, 255).astype( image.dtype )
```

![out00168 4](https://user-images.githubusercontent.com/8076202/37697410-2ef8969e-2cf6-11e8-9668-439ad8b60e92.png)
