### ISSUE TITLE
questions about Epoch and Iteration

### ISSUE THREAD

**Issue by xiangcong** [deepfakes/faceswap#337]
The project is awesome!
But I'm confused with the terms "epoch" and "iteration".
I think all the "epoch" in the project must be "iteration".
In my opinion, "iteration" is for "one" min-batch, and "epoch" is for the entire dataset.
Not sure if it is right?

**Comment by h1vem1nd85** [comment]
You are correct. Its a bit of a misnomer the way training is currently implemented. An epoch is batches over the entire dataset. In order to use the epochs arg as true epochs in training the training.py for each model plugin would need to be adapted to use model.fit rather than train_on_batch. This is fairly easy to implement I just havent gotten around to.

model.fit gives us access to keras callbacks which can dynamically adjust the training rate but has issues with resuming training as the new training rate cannot be saved. Ideally we should use fit_generator and utilizing keras built in image augmentation

**Comment by xiangcong** [comment]
Clear explanation! Thanks ~
