### ISSUE TITLE
Consider interpolating detected face regions across detection gaps

### ISSUE THREAD

**Issue by rifterbater** [deepfakes/faceswap#376]
This wouldn't work for all cases and it's probably a pain to implement given how things are processed frame-by-frame, but for cases where there are single or just a couple frames with no faces detected in the middle of a sequence with faces, there could be an option to interpolate the face locations. Basically assume for very short breaks in face detection that the face region interpolates linearly between the detected locations on either side of the break. May be a relatively straightforward way to increase the robustness of face detection a lot.

**Comment by Kirin-kun** [comment]
https://github.com/iperov/OpenDeepFaceSwap has an optional feature allowing to place the landmarks manually if the face is not detected.

I played with it and it's really cool. Add in the fact that you can work on a subset of frames because the landmarks are embedded in the aligned pngs in that fork and it becomes easy to get the faces you missed.

Your solution involves looking at the pictures in a sliding time window and besides it only applies to video, whereas extraction can apply to random pictures. And it would add faces where there's no one.
