### ISSUE TITLE
Embedding facial landmarks in the alpha channel.

### ISSUE THREAD

**Issue by linkoid** [deepfakes/faceswap#397]
So the idea is to help out the generative network by doing some of the hard work for it, and to determine facial landmarks. The landmarks are placed in the alpha channel much like they are placed in the red channel when you enable "debug facial landmarks" in extract. (Ideally this should be done when they are extracted, however for now I have made a small script to do it to faces post-extraction.) This way when the training data is "warped" the landmark information is properly warped with it. The alpha channel is then fed into the generator as normal, and because the alpha channel is not taken into consideration when calculating loss, it dosen't get confused by the alpha channel (I think).

I have already managed to get a working model, and it very quickly took hold of basic facial poses. After about 2 hours of training it had a good grasp of open vs closed mouths, general facing direction, and even side profiles (which the original model had much difficulty with).

Each facial land mark has it's own value, starting at 256-22 (234 if you hate arithmetic), and decreases by intervals of 6. (256-28, 256-34, etc.) Landmarks that have a mirrored equivalent are just given the same value, therefore instead of needing to input 68 unique landmarks there are only 39. I had to change a couple of other scripts to get images with alpha channels into the training process, and I'm also not completely certain of what happens to the alpha channel after it comes out of the decoder. 

What I don't quite understand is any issues that may arise from running an alpha channel into the program (not just the generator) and expecting it to not treat it as a "transparency channel."

**Comment by AbysmalBiscuit** [comment]
Hey, this is an interesting idea, but wouldn't it be possible/have you tried to just embed the information as metadata into the images, or to have it read from the `alignments.json` file if available?

I'm not sure if such an approach would slow down the training process, but it would allow for avoiding the issues you mentioned with how the alpha channel will get treated. Python dictionaries support random access so I don't think that it should cause too much of a slowdown.
The only big issue I can think of is when you have a data-set made from many videos/images, hence you don't have an `alignments.json` file for the combined dataset, so a tool that lets you merge/modify `alignments.json` files could be useful (@torzdf had started developing one a while ago, but since there wasn't much interest it was never finished).

**Comment by Kirin-kun** [comment]
@iperov already coded it in his fork. The landmarks are embedded in the txt of the pngs of the extracted faces.

**Comment by iperov** [comment]
can't understand what you want :D
all models in my fork trains to predict mask from rgb

**Comment by torzdf** [comment]
@linkoid, you raise some interesting ideas. If you are able to create a working model, then please submit to the repo. We can even put it in staging if it's not fully working and you want other people to help.

In the meantime, I'm closing this issue, but feel free to re-open if you make any progress.
