### ISSUE TITLE
discard frames not containinf faces not working

### ISSUE THREAD

**Issue by fetchlister** [deepfakes/faceswap#398]
I am trying to lean out my deepfake creation time by killing off the frames that don't have faces during the convert, but from everything I've read I seem to be doing it corrently (I assume) but I'm getting no results - all frames are output.

heres a sample command: python faceswap.py convert -b 15 -e 10 -i ~/Desktop/VLC/ -o '/home/luke/Desktop/VLC2' **-fr 0001-10758 -d** -v -m '/home/luke/Videosdeepfakes/MODEL'

Any Ideas?

**Comment by Kirin-kun** [comment]
There's no such option.  If no faces are found in a frame, it's just copied as-is. If you don't want them, remove them from the source.

**Comment by torzdf** [comment]
You can, but I've never really seen the point (nor used it, so can't be sure if it works correctly).

Frames that don't have faces will not be converted anyway, assuming that you have an alignments.json, so they are just copied 'as is', so really shouldn't slow the process down.

In terms of the -fr and -d option. The above code:
`-fr 0001-10758 -d`

Means that you want to process all frames in the range 0001-10758. I assume that this is your entire dataset, so that will have no effect. You are effectively telling it to process the entire range.

Let's say you just wanted to process frames 100-300, you would put:
`-fr 0100-0300`

This would faceswap on those faces and frames 0001 to 0099 and 0301-10758 would be written out as is. If you added in the -d flag then those frames would just be skipped altogether.

As @Kirin-kun says, if you're going to identify them for passing into the process, then you might as well just remove them from source.

**Comment by torzdf** [comment]
It would be possible to identify frames without faces by parsing the alignments.json file. There is no tool to do that, currently, although I started working on one that did various actions based on the content of the file. When I've finished my GUI revamp, I may revisit it.
