### ISSUE TITLE
Install went fine, extraction fine, training no errors but no feedback either.

### ISSUE THREAD

**Issue by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [deepfakes/faceswap#543]
(i answered all of the items in the post outline form below, but i just condensed to paragraph)

Hey, thanks for the awesome program (cool gui as well) I came from openswap, and this gui is great cant wait to delve into the alignments file operations and maintenance options. (even though ill probably use the console, its nice having a gui to quickly visualize and save configs)

Anyway, so I had an issue with splicing first, I ended up just using ffmpeg on a separate machine and porting the stills over. Extraction went just fine, lots of faces found etc. After removing the false positives, I went to train, however it never showed any progress after a half an hour. I switched to 25 save interval, still nothing. I am using original trainer, batch 64. I am working with a k80, and usually that can breeze through the first 100 iterations in less than a couple minutes. So I think something is wrong. I'm also seeing very low cpu usage in task manager, and usually it would be almost maxed out when training in the past.

I followed the windows installation guide to a T, have all the proper drivers/cuda/cudnn/py3.5 versions, all recognized etc. ATX yes etc. The extraction went fine, so not sure why training is not showing anything. I used the verbose option, but cant really see any output anywhere at all. 

Any ideas? thanks.

**Comment by torzdf** [comment]
Get the latest version of the code and try again. You can try to set logging to debug (or even trace if you're brave), but you may not glean much more information as logging is not yet fully implemented for training.

Generally, when it silently freezes, it's a memory allocation issue, which has silently failed in the background without raising the error, so you could try lowering your batch size to 16 and going from there.

Otherwise, as this seems to be quite a user specific issue, you can try looking for help on the Discord server where there may be someone who has a similar setup:
https://discord.gg/FdEwxXd

**Comment by Lu233** [comment]
@IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd , is this issue already fixed on your side? if yes, could you please share your solution?  I am having the same issue. Everything seems fine but nothing is being updated. However the GPU shows it is in use.
