### ISSUE TITLE
Tensorflow currently has no official prebuild for your CUDA

### ISSUE THREAD

**Issue by fetchlister** [deepfakes/faceswap#621]
I had an issue with setup.py ( the following )
INFO    CUDA version: 9.0
INFO    cuDNN version: 7.0.4
WARNING Tensorflow currently has no official prebuild for your CUDA, cuDNN combination.
        Either install a combination that Tensorflow supports or build and install your own tensorflow-gpu.
        CUDA Version: 9.0
        cuDNN Version: 7.0
        Help:
        Building Tensorflow: https://www.tensorflow.org/install/install_sources
        Tensorflow supported versions: https://www.tensorflow.org/install/source#tested_build_configurations

and I was advicsed to just install cudnn 7.4 and then my issue was closed. However in the readme it says not to go above version 9.0.x of cuda and version 7.4 of cudnn requires cuda 10. Can someone attempt to help me here without automatically assuming their suggestion works and closing my bug report?

**Comment by torzdf** [comment]
And I'm closing again, because
1) this is not an issue
2) the correct locations are shown in INSTALL.md
3) You have already been told the correct versions to get.

To be safe, install the version closest to or above 7.2 that you can find.

Tensorflow site explicitily says you need a version greater or equal to 7.2:
![image](https://user-images.githubusercontent.com/36920800/53299449-2f06b600-3832-11e9-8a7e-26811487583e.png)


Any of these version of cuDNN available from the Nvidia cuDNNsite will work
![image](https://user-images.githubusercontent.com/36920800/53299436-ef3fce80-3831-11e9-8264-b7f7131bb104.png)
