### ISSUE TITLE
Installation manual step by step

### ISSUE THREAD

**Issue by gavrilka** [deepfakes/faceswap#72]
Hello everyone. More than a week i am trying to run this project, but i am having troubles.. i even deleted my python and pycharm to reinstall in again, but again no success. Right now, i can't install tensorflow-pgu package. it says "binascii.Error: Incorrect padding". Before was trouble with dlib, but reinstall python and pycharm helped with this.
I am praying someone to help with installation manual, step by step... thank u a lot! i will not give up, this project is awesome!

**Comment by q7v6rhgfzc8tnj3d** [comment]
what is your problem right now ?

**Comment by gavrilka** [comment]
can't install tensorflow-gpu
binascii.Error: Incorrect padding

**Comment by q7v6rhgfzc8tnj3d** [comment]
I would suggest that you try to install the cpu version of tensorflow because installing the gpu version on windows is a hell of a mess. I just assume that you try that on windows, if that is not the case tell me. but otherwise do try the cpu version it is easier to install. the only downside is that it will run slower. if you are serious about tensorflow gpu switch to linux.

**Comment by gavrilka** [comment]
Yes. i am using windows 10 x64. Ok thanks i understand, will keep waiting tensorflow-gpu stable for windows

**Comment by Clorr** [comment]
Closing this if no more info is required
