### ISSUE TITLE
Which paper did the project depend on?

### ISSUE THREAD

**Issue by tjusxh** [deepfakes/faceswap#73]
Please Which paper did the project depend on? I want to see the result.

**Comment by q7v6rhgfzc8tnj3d** [comment]
I think it is that paper: https://arxiv.org/abs/1511.05644

but I am not sure. It looks like he is using some kind of autoencoder. let me know when you find more.

**Comment by petergerten** [comment]
Anyone found more information on this?

**Comment by q7v6rhgfzc8tnj3d** [comment]
https://arxiv.org/pdf/1312.6114.pdf

could be this one.

**Comment by Clorr** [comment]
The code is based on an autoencoder, but not a variational nor an adversarial one. It is made with convolution layers, but does not use pooling which is strange because pooling is very common after conv layers. I don't know if it was based on a specific paper, you should try asking on reddit to /u/deepfakes directly
