### ISSUE TITLE
just run at cuda9.0?? 

### ISSUE THREAD

**Issue by aaronkingdom** [deepfakes/faceswap#755]
hi guys, its can just run at cuda9.0 mode?
my driver is nvidia studio driver, the newest one..
if i change to cuda9.0, im worry about that i cant use in my premiere and after effect...
i can run the gui,  but it seems cant work

**Comment by bryanlyon** [comment]
Cuda 10 is workable but may require extra troubleshooting and work.  This may include a custom compiled tensorflow (though i believe that a working cuda 10 version is compiled).  You may also lose graphing due to changes in how tensor works in newer versions.  For beginners we recommend cuda 9 as installed by the installer.  We intend to migrate to cuda 10 in the future, but it's just started becoming usable.

**Comment by torzdf** [comment]
Both are now fully supported.

**Comment by aaronkingdom** [comment]
ok,  thank you guys!! i will learn more
