### ISSUE TITLE
Handle better shapes for face replacement (Not just a rectangle)

### ISSUE THREAD

**Issue by Clorr** [deepfakes/faceswap#8]
The rectangle gives an artificial look at the generated image, so it would be a nice feature to use a more soft shape.

[This page](https://www.learnopencv.com/face-swap-using-opencv-c-python/) shows a couple of interesting tricks like: landmarks detection, hull detection, seamless cloning....

(Note: If needed, landmarks are already handled in the aligner class)

**Comment by deepfakes** [comment]
I added a first draft for this. It sometimes gives better results, but it can be improved...

Note: In order to use it, you will have to DL the landmarks file from Dlib
http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2

![505546486](https://user-images.githubusercontent.com/34667098/34201737-c18a30e4-e575-11e7-9fa9-3fd89bf35951.jpg)

![831982426](https://user-images.githubusercontent.com/34667098/34201739-c19cd064-e575-11e7-9e66-c2b013c54e97.jpg)

**Comment by Clorr** [comment]
See here: https://www.reddit.com/r/deepfakes/comments/7leh8c/opencv_seamlessclone_is_pure_magic/

**Comment by Clorr** [comment]
Closing this since we have a decent face merge with #30 and that the seamless clone is part of the face align script (#16)
