### ISSUE TITLE
one/few shot approaches, face swapping video from a single image

### ISSUE THREAD

**Issue by ak9250** [deepfakes/faceswap#862]
recent one/few shot approaches seems promising for swapping faces into video from a single image such as https://github.com/shaoanlu/fewshot-face-translation-GAN
can ideas from here to used to improve FS or look into one model to swap all faces instead of training two face pairs, possibly a long term project

**Comment by haarissiddiqie1** [comment]
Hi all,
Yes I think that one shot learning with GAN, would be useful in understanding, Especially with the recent GAO faceswap app.
Best regards, Haaris Siddiqie 

    On Wednesday, 4 September 2019, 15:50:50 BST, ak9250 <notifications@github.com> wrote:  
 
 
recent one/few shot approaches seems promising for swapping faces into video from a single image such as https://github.com/shaoanlu/fewshot-face-translation-GAN
can ideas from here to used to improve FS or look into one model to swap all faces instead of training two face pairs, possibly a long term project

**Comment by torzdf** [comment]
It's possible. These kinds of discussions are best placed in our [FaceSwap Forum](https://faceswap.dev/forum) or [FaceSwap Discord server](https://discord.gg/FC54sYg)
