### ISSUE TITLE
Black screen and hard crash when sorting

### ISSUE THREAD

**Issue by blvck-mvgic** [deepfakes/faceswap#931]
Trying to do Tools > Sort with default options always crashes the whole PC, no matter what
Shortly after picking the input and output dir and starting the sort the screen turns black and turning off the PC by long-pressing the button is impossible, it only turns off by pulling the cord
No log included as there is no time to write any sort_log or crash log before crashing

## Expected behavior

Actually do the sort

## Actual behavior

Hard crash and system unresponsive

## Steps to reproduce

Open faceswap gui
Go to Tools > Sort
Pick input and output dir
Start sorting

## Other relevant information
- Nvidia backend (GTX 1060 6GB)
- Training works like a charm
- Latest windows release (faceswap_setup_x64.exe)
- Crashes 100% of the time

**Comment by SharkEzz** [comment]
Are you using the latest NVIDIA drivers?
Otherwise, you can always try to completely uninstall the drivers (with DDU for example) and then reinstall them to see if there is any improvement.
It can also be an hardware issue, you can check the Windows Event Viewer to see if there is any error messages related to the GPU.
Have you experienced any issues with your graphic card before ?

**Comment by torzdf** [comment]
This sounds like a Power/Hardware issue.
