### ISSUE TITLE
Reason for excluding Python 3.8

### ISSUE THREAD

**Issue by tarnh** [deepfakes/faceswap#939]
What's the reason for excluding Python 3.8 in the moment? An known incompatibility or just a check which hasn't been updated?

**Comment by bryanlyon** [comment]
We rely on a large number of libraries and with each Python version update, it takes time to verify that each library is updated and working on the newest version before we move everyone to that version.  We typically value stability over being on the cutting edge.  That said, we highly recommend using Conda so that each environment can run on different versions, this way your base system can use the latest Python version while Faceswap stays at a supported version without interference.

You are of course welcome with overriding the defaults and trying 3.8 and if you run into any problems, we'd appreciate a bug report letting us know any issues you run into.

**Comment by tarnh** [comment]
I don't bother with (Ana)Condas. On my system I have ~700 python packages installed and there are zero conflicts; so I don't understand the need for env's.

**Comment by torzdf** [comment]
Bookmark this comment. Then the future you can come and shake his head in dismay at the past you.

Up until recently Tensorflow didn't even support Python 3.7. We will upgrade when we upgrade.
