### ISSUE TITLE
No alignments file found

### ISSUE THREAD

**Issue by chenbinghui1** [deepfakes/faceswap#984]
Hi, when i am doing "convert". it tells me No alignments file found.
The command I used is:
python3 faceswap.py convert -i ~/faceswap/src/trump/ -o ~/faceswap/converted/ -m ~/faceswap/trump_cage_model/

The console output is :
03/11/2020 10:39:30 ERROR    No alignments file found. Please provide an alignments file for your destination video (recommended) or enable on-the-fly conversion (not recommended).

I find there is a xx_alignments.fsa file in the input dir. But no alignments.json file. So what should I do then.

**Comment by chenbinghui1** [comment]
I have solved this problem

**Comment by Tian14267** [comment]
Did you run "convert" successfully ? When I run convert ,I get no face picture. Can you help me to sovle it ?
My issue detail  is here: #1002

**Comment by kamil11145** [comment]
@chenbinghui1 
How do you solved the problem?

**Comment by aa3222119** [comment]
@Tian14267 @chenbinghui1  same problem.
How did you solve the problem?

**Comment by flower-King** [comment]
How did you solve the problem?

**Comment by ChrisChross** [comment]
How did you solve it? Please tell us!

**Comment by torzdf** [comment]
Covered, covered and covered again.

RTFM
https://forum.faceswap.dev/viewtopic.php?f=7&t=1083

**Comment by ChrisChross** [comment]
@torzdf your comment reflects the common behavior of human arrogance.
That is im my opinion totally unnecessary as I was just looking for some help.

Leaving the humanities aside, I am using CLI only and the Manuel is only GUI based. 
Nevertheless, I read through it and couldn't find anything about an alignments.json.
Are there some instructions for using CLI only and how to create an alignments.json?

**Comment by gessyoo** [comment]
It's recommended to read the guides several times:  https://forum.faceswap.dev/viewtopic.php?f=7&t=1083 ("As in the other guides, I will be using the GUI, but all the commands here are also available in the cli, You can execute python faceswap.py convert -h to get a list of the commands, and python tools.py -h to get a list of the available tools.").  There is an abundance of useful information in the Faceswap forum.

**Comment by torzdf** [comment]
Sure, you can call me arrogant on a page reserved for issues and bugs. or you could do your own research and find this answer is presented to you in a guide, I wrote for free (and keep updated), to answer one of many questions which is constantly asked, so that I don't need to live in some kind of Groundhog Day answering the same questions again and again and again.

I gave you a link to the solution. I apologise if that has not met your value expectation for the free product I develop in my own time for no financial remuneration.

As @gessyoo alludes to above. The guide is written with the GUI as a contextual device as most of our users use the GUI. However, it is just a front-end for the cli, and everything done in the GUI can be done with the Cli. This is explicitly stated in the opening part of the guide... and then the guide goes on to explicitly cover Alignments files, what they are and how to get them. Here is a direct ink for you: https://forum.faceswap.dev/viewtopic.php?f=7&t=1083#Alignments

I apologise if you still think this is arrogant... but then, what is being presented with an answer and totally ignoring it?

**Comment by ChrisChross** [comment]
Hey @torzdf, 

I feel your depression of having to say it over and over again.
At the same time it should not reflect your response. 
Anyways, thanks for you great work and letting me use it. 
Next time I'll read the manual twice. 

Cheers
Chris

**Comment by ykhasia** [comment]
It seems in the latest version, the "alignments.json" file is replaced by "alignments.fsa" file ? is it correct for my judgement ?

**Comment by torzdf** [comment]
json alignments have not been used in faceswap  for years. Literally, years.

As stated earlier in this thread. Read the guides linked in the faceswap forum as they are kept up to date.

**Installation**
- Windows Installation Guide:: https://faceswap.dev/forum/viewtopic.php?f=4&t=20
- Linux Installation Guide: https://forum.faceswap.dev/viewtopic.php?f=4&t=68
- macOS Installation Guide: https://forum.faceswap.dev/viewtopic.php?t=2748

**Usage**
- Extraction Guide : https://forum.faceswap.dev/viewtopic.php?f=25&t=27
- Training Guide: https://forum.faceswap.dev/viewtopic.php?f=27&t=146
- Convert Guide: https://forum.faceswap.dev/viewtopic.php?f=24&t=1083
